.babelrc
package-lock.json
package.json
script/seed.js
server/db/db.js
server/db/models/Article.js
server/db/models/Author.js
server/db/models/Interaction.js
server/db/models/Publication.js
server/db/models/PublicationType.js
server/db/models/Tag.js
server/db/models/Topic.js
server/db/models/index.js
server/db/models/user.js
server/index.js

- `PublicationType` is equal to "type (newspaper, magazine, blog)" we had on the board. I figured that if Topics had a separate table then Types should too...
- I did not create the `friendships` User-User join table, my understanding is that it's not part of our MVP and it actually brings up some tricky questions re: how to store this information that perhaps we can discuss later.
- The `content` field of the seed article is not the full content of that long New Yorker piece, it's just one paragraph. The actual structure of that article looks something like this:
```html
<div class = "SectionBreak__sectionBreak__1ppA7">
<p></p>
<p></p>
<p></p>
</div>
```

Build db models #1

---

web-app/client/components/AuthForm.js
web-app/client/components/UserHome.js
web-app/client/components/navbar.js
web-app/client/routes.js
web-app/public/style.css

Rearranged Navbar to show a User icon & user's email over on left side when a User is logged in. 
Logout button has been moved to a dropdown under the user's email, along with a link to the user's page.
Integrated Semantic-UI into the AuthForm, added a separate button for eventual Twitter login.

Auth styling

---

web-app/server/db/models/Article.js

Remember to `npm run seed` after pulling in this change as this is a change to our database model.

Fixed `isUrl` validation on `Article` model

---

web-app/client/components/AddForm.js
web-app/client/components/Analytics.js
web-app/client/components/ArticleList.js
web-app/client/components/Home.js
web-app/client/components/NavbarSideItems.js
web-app/client/components/NavbarSideMobile.js
web-app/client/components/NavbarTop.js
web-app/client/components/PageContainer.js
web-app/client/components/index.js
web-app/client/routes.js
web-app/public/style.css

- Created new 'pageContainer' component to wrap pages that should have Sidebar (ie. most pages that are not an Article or Login)
- Add Icons to Sidebar
- Add '+' button to top Navbar and create form component to allow users to add articles from the site (functionality not implemented yet)

Build frontend

---

README.md
web-app/package-lock.json
web-app/package.json

renamed context to readMe in some places

---

web-app/client/app.js
web-app/client/components/PageContainer.js
web-app/public/style.css

- added an extra media query so the `Pusher` container for mobile sidebar is only actually rendered when on mobile view
- changed CSS to fix scroll bug

Article scroll bug

---

web-app/public/style.css
web-app/server/api/articles.js
web-app/server/db/models/Article.js
web-app/utils.js

- Actually fixed this issue on Jeff's branch mercuryErrHandling-#96
- Minor styling

Get article image

---

web-app/client/components/ArticleCard.js
web-app/client/components/ButtonAddArticle.js
web-app/client/components/ButtonChangeStyle.js
web-app/client/components/FormAddArticle.js
web-app/client/components/FormChangeStyle.js
web-app/client/components/NavbarTop.js
web-app/client/components/index.js
web-app/public/style.css

- created a component to let user's change article background color, font, and font size
- functionality NOT implemented yet

create component for changing article styles

---

web-app/package.json
web-app/script/seed.js
web-app/server/api/articles.js
web-app/server/api/interactions.js

- Seed file will now 
- create a bunch of pre-selected articles using the same function as the API route
- create random interactions with the articles under an hour in length over the past year and a half

Seed file buildout

---

web-app/client/components/Article.js
web-app/client/components/FormChangeStyle.js
web-app/client/store/articleStyle.js
web-app/client/store/index.js
web-app/public/style.css

- Implement functionality for the page style selection component
- Article component now renders its styles based on new `articleStyles` state on the Redux store

User styles

---

web-app/client/app.js
web-app/client/components/ButtonAddArticle.js
web-app/client/components/ButtonIcon.js
web-app/client/components/Message.js
web-app/client/components/index.js
web-app/client/store/index.js
web-app/client/store/message.js
web-app/public/style.css

- There is now a reusable `Message` component that can be shown by dispatching `message(string)`. Will automatically fade out after two seconds.
- Add article, archive, delete, and add-back-to-my-list buttons are now disabled if there is no internet connection available.

Service worker

---

web-app/server/db/models/Article.js

- fixed sanitize-html href error

Fix sanitize html

---

web-app/client/components/Home.js
web-app/client/routes.js
web-app/client/store/articlesAll.js
web-app/script/testDbAggQueries.js
web-app/server/api/articles.js
web-app/server/db/models/Article.js
web-app/server/db/models/Interaction.js
web-app/server/utils.js

- Fixed bug where publication does not appear on archived article after archiving (and refactored/moved logic to `Article` db model in the process)
- Fixed bug where initial login displays none of the user's articles.
- Added `clearInterval` for internet connection checking interval, just to be safe - I noticed on rare occasions that the connection events seem to over-dispatch
- Added `paranoid` rule to `Article` model so that records are not destroyed; instead, they have a `deletedAt` value (make sure to re-seed db). The non-raw-SQL `Interaction` query which includes `Article` has been updated to include the deleted article as well.
- Replaced hacky `alert()` box with new sexy `message()` dispatch when `POST` fails

Various bug fixes

---

web-app/client/components/Analytics.js
web-app/client/components/AnalyticsChart.js
web-app/client/components/AnalyticsVisual.js
web-app/client/components/index.js

Analytics tab containers

---

web-app/client/components/ArticleList.js
web-app/client/routes.js
web-app/service-worker.js

- Remove `dispatch(fetchArticles())` from `routes`
- Add `dispatch(fetchArticles())` to `ArticleList` component
- move around code in service worker to fix bug where cached response was not always being served when server does not respond

service worker bug fixes

---

web-app/client/app.js
web-app/client/components/Article.js
web-app/client/components/ArticleCard.js
web-app/client/components/ArticleList.js
web-app/client/components/ArticleListItem.js
web-app/client/components/ButtonArchiveArticle.js
web-app/client/components/ButtonDeleteArticle.js
web-app/client/components/ButtonIcon.js
web-app/client/components/ButtonMyListArticle.js
web-app/client/components/ButtonUserIcon.js
web-app/client/components/FormAddArticle.js
web-app/client/components/NavbarSideItems.js
web-app/client/components/NavbarSideMobile.js
web-app/client/components/NavbarTop.js
web-app/client/components/PageContainer.js
web-app/client/components/VisContainer.js
web-app/client/components/index.js
web-app/client/history.js
web-app/client/store/index.js
web-app/client/store/pageScroll.js
web-app/public/style.css

- Users will receive a confirmation message when archiving, deleting, or adding an article
- Article status buttons have a fade-in/fade-out animation
- There is a 'back' button at the bottom of each article
- Navbar fades away when scrolling down on both article and article lists, reappears on scroll up
- User's email address is hidden when on mobile to free up space on navbar; dropdown menu comes from icon instead.
- Scrolling on mobile now feels more natural -- refactored out the entire `Sidebar` semantic-ui component that had been a pain to work with, and reimplemented show/hiding the mobile sidebar with semantic ui transitions

Ui enhancements

---

web-app/client/components/Analytics.js
web-app/client/components/LandingPage.js
web-app/client/components/ReadingSources.js
web-app/client/components/ReadingTimeGraphs.js
web-app/client/components/index.js
web-app/client/store/analytics.js
web-app/client/utils/visualizationStyles.js
web-app/package.json
web-app/server/api/interactions.js

- get publication counts DB method
- publications action creators / thunks
- _start_ of pie chart for reading sources analytics tab

create pie chart for publication counts

---

web-app/client/components/ReadingTimeline.js

- fixed x axis of reading timeline

Fix timeline

---

browser-ext/chrome/src/js/background.js
browser-ext/chrome/src/manifest.json
web-app/server/index.js

- Point Chrome ext API call to deployed Heroku address

Chrome ext heroku

---

README.md

write readme for readMe ;)

---

web-app/client/components/AuthForm.js
web-app/client/components/AuthFormLocal.js
web-app/client/components/FieldWithWarning.js
web-app/client/components/SignupOrLoginForm.js
web-app/client/components/index.js
web-app/client/store/index.js
web-app/client/store/user.js
web-app/client/utils/formValidations.js
web-app/package-lock.json
web-app/package.json
web-app/public/style.css
web-app/server/auth/google.js
web-app/server/auth/index.js
web-app/server/db/models/User.js

This addresses subtasks 1, 2, and 4 in #162 .
The most significant change in this commit is integrating [Redux-Form](https://redux-form.com/6.0.0-alpha.4/docs/gettingstarted.md/) which adds a `form` property to state. Using its `Field` component (which itself can render any component we want, such as Semantic's `Input`) allows us to pass in an array of validating functions:
```js
import { Field, reduxForm } from 'redux-form';
import {
isFilledOut,
isEmail,
} from '../utils/formValidations';
<Field
component={FieldWithWarning}
name="email"
type="text"
placeholder="Email"
validate={[isFilledOut, isEmail]} // <-----THIS
/>
```
In other words, we now have validation on the front end that the user is entering a valid email address, as well as a strong password. Password strength (and hints for …

User signup/login form and db model validations, update dependencies
